const websites = [
  {
    id: 1,
    nameKey: "selected_work.name.salon_beauty",
    typeKey: "selected_work.type.salon_beauty",
    category: "salon-beauty",
    descKey: "selected_work.projects.blanche_desc",
    image:
      "https://images.unsplash.com/photo-1707979577466-2d6109c68a45?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "https://blanche-hair-salon.netlify.app/",
    location: "Freiburg, Germany",
    tags: ["React", "Responsive", "Booking System", "CSS", "JavaScript"],
    status: null,
    live_demo: "https://blanche-bice.vercel.app/",
  },
  {
    id: 2,
    nameKey: "selected_work.name.restaurant_cafe",
    typeKey: "selected_work.type.restaurant_cafe",
    category: "restaurant-cafe",
    descKey: "selected_work.projects.terra_desc",
    image:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "https://terra-restaurant-sigma.vercel.app/",
    location: "Berlin, Germany",
    tags: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Responsive",
      "Reservation System",
    ],
    status: null,
    live_demo: "https://terra-restaurant-sigma.vercel.app/",
  },
  {
    id: 3,
    nameKey: "selected_work.name.medical_health",
    typeKey: "selected_work.type.medical_health",
    category: "medical-health",
    descKey: "selected_work.projects.dr_med_schmidt_desc",
    image:
      "https://images.unsplash.com/photo-1629909613654-28e377c37b09?q=80&w=2068&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "https://github.com/ilkckn/House-Doctor",
    location: "Lörrach, Germany",
    tags: [
      "React",
      "Responsive",
      "CSS",
      "JavaScript",
      "React Router",
      "Leaflet",
    ],
    status: null,
    live_demo: "https://dr-med-schmidt.vercel.app/",
  },
  {
    id: 4,
    nameKey: "selected_work.name.fitness_gym",
    typeKey: "selected_work.type.fitness_gym",
    category: "fitness-gym",
    descKey: "selected_work.projects.iron_pulse",
    image:
      "https://images.unsplash.com/photo-1591311630200-ffa9120a540f?q=80&w=1620&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "https://github.com/ilkckn/Iron-Pulse",
    location: "New York, USA",
    tags: [
      "React",
      "Responsive",
      "CSS",
      "JavaScript",
      "React Router",
      "Leaflet",
    ],
    status: null,
    live_demo: "https://iron-puls.vercel.app/",
  },
  {
    id: 5,
    nameKey: "selected_work.name.cafe_ember",
    typeKey: "selected_work.type.cafe_ember",
    category: "restaurant-cafe",
    descKey: "selected_work.projects.ember_desc",
    image:
      "https://images.unsplash.com/photo-1655182413225-695cc7ed0411?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    link: "https://github.com/ilkckn/Ember-Cafe",
    location: "Portland, USA",
    tags: ["React", "Responsive", "CSS", "JavaScript", "React Router"],
    status: null,
    live_demo: "https://ember-cafe-xi.vercel.app/",
  },
  {
    id: 6,
    nameKey: "selected_work.name.butchers_block",
    typeKey: "selected_work.type.butchers_block",
    category: "retail",
    descKey: "selected_work.projects.butchers_block_desc",
    image: "/the-butchers-block.png",
    link: "https://github.com/ilkckn/The-Butcher-s-Block",
    location: "Frankfurt, Germany",
    tags: [
      "React",
      "Responsive",
      "CSS",
      "JavaScript",
      "React Router",
      "Context API",
      "WhatsApp Ordering",
    ],
    status: "latest",
    live_demo: "https://the-butcher-s-block.vercel.app/",
  },
];

export default websites;
